language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install pep8 pyflakes pylint
  - pip install coverage coveralls
script: make test coverage
after_success:
  - coveralls
notifications:
  email: false
